velodyne_driver_node:
    ros__parameters:
        device_ip: 192.168.67.202
        gps_time: false
        time_offset: 0.0
        enabled: true
        read_once: false
        read_fast: false
        repeat_delay: 0.0
        frame_id: velodyne
        model: VLP16
        rpm: 600.0
        port: 2268
        timestamp_first_packet: false
